locations = [
    {
        "name": "ARC-L1 Wide Forest Station",
        "system": "ArcCorp",
        "station": "ARC-L1",
        "location_type": "STATION",
    },
    {
        "name": "Everus Harbor",
        "system": "Hurston",
        "station": "Lorville",
        "location_type": "STATION",
    },
    {
        "name": "Port Tressler",
        "system": "MicroTech",
        "station": "New Babbage",
        "location_type": "STATION",
    },
    {
        "name": "Sacren's Plot",
        "system": "Pyro",
        "station": "Sacren's Plot",
        "location_type": "OUTPOST",
    },
    {
        "name": "Rat's Nest",
        "system": "Pyro",
        "station": "PYR5-L5",
        "location_type": "STATION",
    },
    {
        "name": "Rod's Fuel",
        "system": "Pyro",
        "station": "PYR5-L4",
        "location_type": "STATION",
    },
    {
        "name": "Patch City",
        "system": "Pyro",
        "station": "PYR3-L3",
        "location_type": "STATION",
    },
    {
        "name": "Endgame",
        "system": "Pyro",
        "station": "PYR6-L3",
        "location_type": "STATION",
    },
    {
        "name": "Jackson's Swap",
        "system": "Pyro",
        "station": "Jackson's Swap",
        "location_type": "OUTPOST",
    },
    {
        "name": "Dudley and Daughters",
        "system": "Pyro",
        "station": "PYR6-L4",
        "location_type": "STATION",
    },
    {
        "name": "Canard View",
        "system": "Pyro",
        "station": "Terminus",
        "location_type": "OUTPOST",
    },
    {
        "name": "The Golden Riviera",
        "system": "Pyro",
        "station": "Bloom",
        "location_type": "OUTPOST",
    },
    {
        "name": "TDD Area 18",
        "system": "ArcCorp",
        "station": "Area 18",
        "location_type": "CITY",
    },
    {
        "name": "TDD New Babbage",
        "system": "Microtech",
        "station": "New Babbage",
        "location_type": "CITY",
    },
    {
        "name": "CBD Lorville",
        "system": "Hurston",
        "station": "Lorville",
        "location_type": "CITY",
    },
    {
        "name": "TDD Orison",
        "system": "Crusader",
        "station": "Orison",
        "location_type": "CITY",
    },
    {
        "name": "Stanton Gateway (Nyx)",
        "system": "Nyx",
        "station": "NYSTJP",
        "location_type": "STATION",
    },
    {
        "name": "Levski",
        "system": "Nyx",
        "station": "Delamar",
        "location_type": "STATION",
    },
    {
        "name": "Brio's Breaker",
        "system": "Crusader",
        "station": "Daymar",
        "location_type": "OUTPOST",
    },{
        "name": "GrimHEX",
        "system": "Crusader",
        "station": "Yela",
        "location_type": "STATION",
    },
    {
        "name": "CRU-L5 Maintenance",
        "system": "Crusader",
        "station": "CRU-L5",
        "location_type": "STATION",
    },
    {
        "name": "Nyx Gateway (Pyro)",
        "system": "Pyro",
        "station": "PYNYJP",
        "location_type": "STATION",
    },
    {
        "name": "Deakins Research",
        "system": "Crusader",
        "station": "Yela",
        "location_type": "OUTPOST",
    },
    {
        "name": "Terra Mills",
        "system": "Crusader",
        "station": "Cellin",
        "location_type": "OUTPOST",
    },
    {
        "name": "ArcCorp141",
        "system": "Crusader",
        "station": "Daymar",
        "location_type": "OUTPOST",
    },
    {
        "name": "ArcCorp157",
        "system": "Crusader",
        "station": "Yela",
        "location_type": "OUTPOST",
    },
    {
        "name": "Rayari Kaltag",
        "system": "Microtech",
        "station": "Calliope",
        "location_type": "OUTPOST",
    },
    {
        "name": "Hickes Research",
        "system": "Crusader",
        "station": "Cellin",
        "location_type": "OUTPOST",
    },
    {
        "name": "Rayari Anvik",
        "system": "Microtech",
        "station": "Calliope",
        "location_type": "OUTPOST",
    },
    {
        "name": "Ashland",
        "system": "Pyro",
        "station": "PYR5",
        "location_type": "OUTPOST",
    },
    {
        "name": "Fallow Field",
        "system": "Pyro",
        "station": "PYR5",
        "location_type": "OUTPOST",
    },
    {
        "name": "Ruin Station",
        "system": "Pyro",
        "station": "Terminus",
        "location_type": "STATION",
    },
    {
        "name": "Pyro Gateway (Nyx)",
        "system": "Nyx",
        "station": "NPJP",
        "location_type": "STATION",
    },
    {
        "name": "Samson & Son's",
        "system": "ArcCorp",
        "station": "Wala",
        "location_type": "OUTPOST",
    },
    {
        "name": "CRU-L4 Locker Room",
        "system": "Crusader",
        "station": "CRU-L4",
        "location_type": "STATION",
    },
    {
        "name": "CRU-L1 Ambitious Dream Station",
        "system": "Crusader",
        "station": "CRU-L1",
        "location_type": "STATION",
    },
    {
        "name": "HUR-L1 Green Glade Station",
        "system": "Hurston",
        "station": "HUR-L1",
        "location_type": "STATION",
    },
    {
        "name": "HUR-L2 Faithful Dream Station",
        "system": "Hurston",
        "station": "HUR-L2",
        "location_type": "STATION",
    },
    
]
